"""
CrimeGPT-X — Document Generation Service
Renders legal documents from case data using Jinja2 + AI
Supports: Chargesheet, Remand, Panchanama, Seizure Receipt, etc.
"""
from jinja2 import Environment, BaseLoader
from datetime import datetime
import logging

logger = logging.getLogger(__name__)

# ── Jinja2 Environment ───────────────────────────────────────
jinja_env = Environment(loader=BaseLoader(), autoescape=False)
jinja_env.globals['now'] = datetime.now

# ── Shared header/footer template ────────────────────────────
_HEADER = """
<div style="text-align:center;border-bottom:2px solid #333;padding-bottom:12px;margin-bottom:20px">
  <div style="font-size:14px;font-weight:bold;text-transform:uppercase">{{ station }}</div>
  <div style="font-size:11px;color:#555">Gujarat Police — Ahmedabad Cyber Crime Branch</div>
  <div style="font-size:16px;font-weight:bold;margin:10px 0;text-transform:uppercase">{{ doc_title }}</div>
  <div style="font-size:11px">
    FIR No.: <b>{{ fir_number }}</b> &nbsp;|&nbsp;
    Case ID: <b>{{ case_id }}</b> &nbsp;|&nbsp;
    Date: <b>{{ date }}</b>
  </div>
</div>
"""

_FOOTER = """
<div style="margin-top:40px;border-top:1px solid #ccc;padding-top:16px;display:flex;justify-content:space-between">
  <div style="text-align:center">
    <div style="border-top:1px solid #333;width:180px;margin:0 auto;padding-top:4px">{{ io_name }}</div>
    <div style="font-size:10px;color:#555">Investigation Officer<br>Badge: {{ io_badge }}</div>
  </div>
  <div style="text-align:center">
    <div style="border-top:1px solid #333;width:180px;margin:0 auto;padding-top:4px">Station Seal</div>
    <div style="font-size:10px;color:#555">{{ station }}<br>Date: {{ date }}</div>
  </div>
  <div style="text-align:center">
    <div style="border-top:1px solid #333;width:180px;margin:0 auto;padding-top:4px">Supervisor</div>
    <div style="font-size:10px;color:#555">SHO / DySP<br>Ahmedabad Cyber Crime Branch</div>
  </div>
</div>
<div style="text-align:center;margin-top:16px;font-size:10px;color:#888">
  Generated by CrimeGPT-X AI Platform · {{ now().strftime('%d %b %Y %H:%M') }} IST · Confidential
</div>
"""

# ── Document Templates ────────────────────────────────────────
TEMPLATES = {

"chargesheet": """
<div style="font-family:Georgia,serif;max-width:800px;margin:0 auto;padding:24px;color:#111;line-height:1.7">
""" + _HEADER + """
<div style="text-align:center;margin:16px 0">
  <div style="font-size:11px;text-transform:uppercase;letter-spacing:1px">In the Court of the Hon'ble Chief Judicial Magistrate</div>
  <div style="font-size:11px">Ahmedabad, Gujarat</div>
</div>

<div style="margin-bottom:16px">
  <b>UNDER SECTIONS:</b>
  {% for s in ai_sections %}{{ s.section }}{% if not loop.last %}, {% endif %}{% endfor %}
</div>

<h3 style="border-bottom:1px solid #ddd;padding-bottom:6px;margin-bottom:12px">1. Complainant / Victim Details</h3>
<table style="width:100%;border-collapse:collapse;font-size:13px;margin-bottom:16px">
  <tr><td style="width:35%;padding:6px;color:#555">Full Name:</td><td style="padding:6px;font-weight:bold">{{ victim_name }}</td></tr>
  {% if victim_phone %}<tr><td style="padding:6px;color:#555">Mobile Number:</td><td style="padding:6px">{{ victim_phone }}</td></tr>{% endif %}
  {% if victim_address %}<tr><td style="padding:6px;color:#555">Address:</td><td style="padding:6px">{{ victim_address }}</td></tr>{% endif %}
  <tr><td style="padding:6px;color:#555">Amount Defrauded:</td><td style="padding:6px;font-weight:bold;color:#c00">₹{{ "{:,.0f}".format(amount_defrauded) }} ({{ amount_words }})</td></tr>
</table>

<h3 style="border-bottom:1px solid #ddd;padding-bottom:6px;margin-bottom:12px">2. Accused Details</h3>
<table style="width:100%;border-collapse:collapse;font-size:13px;margin-bottom:16px">
  <tr><td style="width:35%;padding:6px;color:#555">Name:</td><td style="padding:6px;font-weight:bold">{{ accused_name }}</td></tr>
  {% if accused_phone %}<tr><td style="padding:6px;color:#555">Contact / Account:</td><td style="padding:6px">{{ accused_phone }}</td></tr>{% endif %}
  {% if accused_address %}<tr><td style="padding:6px;color:#555">Address:</td><td style="padding:6px">{{ accused_address }}</td></tr>{% endif %}
  {% if accused_mode %}<tr><td style="padding:6px;color:#555">Mode of Fraud:</td><td style="padding:6px">{{ accused_mode }}</td></tr>{% endif %}
</table>

<h3 style="border-bottom:1px solid #ddd;padding-bottom:6px;margin-bottom:12px">3. Facts of the Case</h3>
<div style="font-size:13px;margin-bottom:16px;text-align:justify">{{ incident_description }}</div>

<h3 style="border-bottom:1px solid #ddd;padding-bottom:6px;margin-bottom:12px">4. Applicable Legal Sections</h3>
<table style="width:100%;border-collapse:collapse;font-size:12px;margin-bottom:16px">
  <tr style="background:#f5f5f5">
    <th style="padding:8px;text-align:left;border:1px solid #ddd">Section</th>
    <th style="padding:8px;text-align:left;border:1px solid #ddd">Title</th>
    <th style="padding:8px;text-align:left;border:1px solid #ddd">Applicability</th>
    <th style="padding:8px;text-align:center;border:1px solid #ddd">AI Confidence</th>
  </tr>
  {% for s in ai_sections %}
  <tr>
    <td style="padding:8px;border:1px solid #ddd;font-weight:bold">{{ s.section }}</td>
    <td style="padding:8px;border:1px solid #ddd">{{ s.title }}</td>
    <td style="padding:8px;border:1px solid #ddd;color:#444;font-size:11px">{{ s.description }}</td>
    <td style="padding:8px;border:1px solid #ddd;text-align:center">{{ s.confidence }}%</td>
  </tr>
  {% endfor %}
</table>

<h3 style="border-bottom:1px solid #ddd;padding-bottom:6px;margin-bottom:12px">5. Evidence on Record</h3>
<ol style="font-size:13px;padding-left:20px;margin-bottom:16px">
  <li>Digital evidence uploaded and SHA-256 verified as per BSA Section 63</li>
  <li>Bank transaction records showing unauthorized UPI/NEFT transfers</li>
  <li>WhatsApp conversation export and call records</li>
  <li>Victim statement recorded under BNSS Section 180</li>
  <li>Accused device forensic report (pending lab)</li>
</ol>

<h3 style="border-bottom:1px solid #ddd;padding-bottom:6px;margin-bottom:12px">6. Prayer</h3>
<div style="font-size:13px;margin-bottom:16px">
  It is respectfully submitted that the above-named accused be tried under the sections mentioned above.
  The investigation officer prays that this Hon'ble Court may be pleased to take cognizance of the offence
  and issue process as deemed fit and proper in the interest of justice.
</div>

""" + _FOOTER + """
</div>
""",

# ── Remand Request ────────────────────────────────────────────
"remand_request": """
<div style="font-family:Georgia,serif;max-width:800px;margin:0 auto;padding:24px;color:#111;line-height:1.7">
""" + _HEADER.replace("{{ doc_title }}", "APPLICATION FOR POLICE REMAND") + """

<div style="margin-bottom:20px">
  <div>To,</div>
  <div style="margin-left:20px">
    The Hon'ble Chief Judicial Magistrate,<br>
    Ahmedabad, Gujarat.
  </div>
</div>

<div style="margin-bottom:16px">
  <b>Subject:</b> Application for Police Custody Remand of Accused {{ accused_name }} in FIR No. {{ fir_number }}
  under BNS 318, 319, IT Act 66C, 66D.
</div>

<div style="margin-bottom:16px">Most Respectfully Showeth:</div>

<ol style="font-size:13px;padding-left:20px;line-height:2">
  <li>That FIR No. {{ fir_number }} was registered at {{ station }} on {{ date }} in respect of a cyber fraud committed against {{ victim_name }} whereby the accused {{ accused_name }} fraudulently caused a loss of <b>₹{{ "{:,.0f}".format(amount_defrauded) }}.</b></li>
  <li>That the accused has been arrested on the basis of digital evidence linking him to the aforesaid crime, including UPI transaction records, WhatsApp call logs, and AnyDesk session data.</li>
  <li>That the following investigation aspects require police custody:
    <ul style="margin-top:8px;line-height:1.8">
      <li>Forensic analysis of accused's mobile device and laptop</li>
      <li>Tracing of mule bank accounts used to siphon funds</li>
      <li>Identification of co-conspirators (organized cyber fraud gang suspected)</li>
      <li>Recovery of fraudulently obtained amount</li>
      <li>Verification of accused's other alleged frauds (pattern of activity detected)</li>
    </ul>
  </li>
  <li>That the accused may tamper with digital evidence or influence witnesses if released.</li>
  <li>That the applicant therefore prays that this Hon'ble Court may be pleased to grant <b>Police Custody Remand for 7 (Seven) Days</b> as required for effective investigation.</li>
</ol>

<div style="margin:20px 0;font-size:13px">
  <b>Relevant Legal Provisions:</b> BNSS Section 187 (Police Custody), IT Act 66C &amp; 66D (Cyber Offences)
</div>

""" + _FOOTER + """
</div>
""",

# ── Panchanama ────────────────────────────────────────────────
"panchanama": """
<div style="font-family:Georgia,serif;max-width:800px;margin:0 auto;padding:24px;color:#111;line-height:1.7">
""" + _HEADER.replace("{{ doc_title }}", "ACCUSED PANCHANAMA (पंचनामा)") + """

<div style="margin-bottom:16px">
  This Panchanama was prepared on <b>{{ date }}</b> at <b>{{ station }}</b> in the presence of the following Panchas (witnesses):
</div>

<table style="width:100%;border-collapse:collapse;font-size:13px;margin-bottom:20px">
  <tr style="background:#f5f5f5">
    <th style="padding:8px;border:1px solid #ddd">Sr.</th>
    <th style="padding:8px;border:1px solid #ddd">Pancha Name</th>
    <th style="padding:8px;border:1px solid #ddd">Address</th>
    <th style="padding:8px;border:1px solid #ddd">Occupation</th>
    <th style="padding:8px;border:1px solid #ddd">Signature</th>
  </tr>
  <tr>
    <td style="padding:8px;border:1px solid #ddd;text-align:center">1</td>
    <td style="padding:8px;border:1px solid #ddd">________________________</td>
    <td style="padding:8px;border:1px solid #ddd">________________________</td>
    <td style="padding:8px;border:1px solid #ddd">________________________</td>
    <td style="padding:8px;border:1px solid #ddd">________________________</td>
  </tr>
  <tr>
    <td style="padding:8px;border:1px solid #ddd;text-align:center">2</td>
    <td style="padding:8px;border:1px solid #ddd">________________________</td>
    <td style="padding:8px;border:1px solid #ddd">________________________</td>
    <td style="padding:8px;border:1px solid #ddd">________________________</td>
    <td style="padding:8px;border:1px solid #ddd">________________________</td>
  </tr>
</table>

<h3 style="margin-bottom:10px">Accused Particulars</h3>
<table style="width:100%;border-collapse:collapse;font-size:13px;margin-bottom:20px">
  <tr><td style="width:30%;padding:8px;background:#f9f9f9;border:1px solid #ddd">Name</td><td style="padding:8px;border:1px solid #ddd;font-weight:bold">{{ accused_name }}</td></tr>
  <tr><td style="padding:8px;background:#f9f9f9;border:1px solid #ddd">Address</td><td style="padding:8px;border:1px solid #ddd">{{ accused_address or 'Under Investigation' }}</td></tr>
  <tr><td style="padding:8px;background:#f9f9f9;border:1px solid #ddd">Mobile</td><td style="padding:8px;border:1px solid #ddd">{{ accused_phone or 'Unknown' }}</td></tr>
  <tr><td style="padding:8px;background:#f9f9f9;border:1px solid #ddd">Arrested At</td><td style="padding:8px;border:1px solid #ddd">________________________</td></tr>
  <tr><td style="padding:8px;background:#f9f9f9;border:1px solid #ddd">Time of Arrest</td><td style="padding:8px;border:1px solid #ddd">________________________</td></tr>
</table>

<h3 style="margin-bottom:10px">Articles Seized from Accused</h3>
<table style="width:100%;border-collapse:collapse;font-size:13px;margin-bottom:20px">
  <tr style="background:#f5f5f5">
    <th style="padding:8px;border:1px solid #ddd">Sr.</th>
    <th style="padding:8px;border:1px solid #ddd">Article Description</th>
    <th style="padding:8px;border:1px solid #ddd">Make/Model</th>
    <th style="padding:8px;border:1px solid #ddd">IMEI/Serial</th>
    <th style="padding:8px;border:1px solid #ddd">Condition</th>
  </tr>
  <tr>
    <td style="padding:8px;border:1px solid #ddd;text-align:center">1</td>
    <td style="padding:8px;border:1px solid #ddd">Mobile Phone</td>
    <td style="padding:8px;border:1px solid #ddd">________________________</td>
    <td style="padding:8px;border:1px solid #ddd">________________________</td>
    <td style="padding:8px;border:1px solid #ddd">Seized</td>
  </tr>
  <tr>
    <td style="padding:8px;border:1px solid #ddd;text-align:center">2</td>
    <td style="padding:8px;border:1px solid #ddd">SIM Card(s)</td>
    <td style="padding:8px;border:1px solid #ddd">________________________</td>
    <td style="padding:8px;border:1px solid #ddd">________________________</td>
    <td style="padding:8px;border:1px solid #ddd">Seized</td>
  </tr>
</table>

<div style="font-size:13px;margin-bottom:20px">
  The above Panchanama was read over to the Panchas, who confirmed its contents to be true and correct, and affixed their signatures.
</div>

""" + _FOOTER + """
</div>
""",

# ── Seizure Receipt ───────────────────────────────────────────
"seizure_receipt": """
<div style="font-family:Georgia,serif;max-width:800px;margin:0 auto;padding:24px;color:#111;line-height:1.7">
""" + _HEADER.replace("{{ doc_title }}", "SEIZURE RECEIPT (जब्ती पावती)") + """

<div style="font-size:13px;margin-bottom:20px">
  Received from <b>{{ victim_name }}</b>, residing at {{ victim_address or '____________________' }},
  the following articles / digital evidence in connection with Case ID: <b>{{ case_id }}</b>.
</div>

<table style="width:100%;border-collapse:collapse;font-size:12px;margin-bottom:20px">
  <tr style="background:#f5f5f5">
    <th style="padding:8px;border:1px solid #ddd">Sl.</th>
    <th style="padding:8px;border:1px solid #ddd">Article / File Description</th>
    <th style="padding:8px;border:1px solid #ddd">File Type</th>
    <th style="padding:8px;border:1px solid #ddd">SHA-256 Hash (first 16 chars)</th>
    <th style="padding:8px;border:1px solid #ddd">Condition</th>
    <th style="padding:8px;border:1px solid #ddd">Received By</th>
  </tr>
  <tr>
    <td style="padding:8px;border:1px solid #ddd;text-align:center">1</td>
    <td style="padding:8px;border:1px solid #ddd">WhatsApp Chat Export</td>
    <td style="padding:8px;border:1px solid #ddd">PDF</td>
    <td style="padding:8px;border:1px solid #ddd;font-family:monospace;font-size:10px">a3f8c2d1e6b5f4a8</td>
    <td style="padding:8px;border:1px solid #ddd">Verified</td>
    <td style="padding:8px;border:1px solid #ddd">{{ io_name }}</td>
  </tr>
  <tr>
    <td style="padding:8px;border:1px solid #ddd;text-align:center">2</td>
    <td style="padding:8px;border:1px solid #ddd">Bank Statement (SBI)</td>
    <td style="padding:8px;border:1px solid #ddd">PDF</td>
    <td style="padding:8px;border:1px solid #ddd;font-family:monospace;font-size:10px">b7d2e5f4a1c3b8d9</td>
    <td style="padding:8px;border:1px solid #ddd">Verified</td>
    <td style="padding:8px;border:1px solid #ddd">{{ io_name }}</td>
  </tr>
  <tr>
    <td style="padding:8px;border:1px solid #ddd;text-align:center">3</td>
    <td style="padding:8px;border:1px solid #ddd">UPI Transaction Screenshots (x2)</td>
    <td style="padding:8px;border:1px solid #ddd">PNG</td>
    <td style="padding:8px;border:1px solid #ddd;font-family:monospace;font-size:10px">c9a1b3e7d2f5a8c4</td>
    <td style="padding:8px;border:1px solid #ddd">Verified</td>
    <td style="padding:8px;border:1px solid #ddd">{{ io_name }}</td>
  </tr>
</table>

<div style="font-size:12px;color:#555;margin-bottom:20px">
  Note: All digital evidence has been hash-verified at the time of seizure. Original files are stored
  in the CrimeGPT-X Evidence Vault with SHA-256 integrity certification as per BSA Section 63(2).
</div>

<div style="display:flex;justify-content:space-between;margin-top:32px;font-size:13px">
  <div>
    <div style="border-top:1px solid #333;width:200px;padding-top:6px">Signature of Complainant / Victim</div>
    <div style="font-size:11px;color:#555">{{ victim_name }}</div>
  </div>
  <div>
    <div style="border-top:1px solid #333;width:200px;padding-top:6px">Receiving Officer</div>
    <div style="font-size:11px;color:#555">{{ io_name }} · {{ io_badge }}</div>
  </div>
</div>
""" + _FOOTER + """
</div>
""",

}

# Aliases
TEMPLATES["purvani_chargesheet"] = TEMPLATES["chargesheet"].replace(
    "CHARGESHEET (आरोप पत्र)", "PURVANI CHARGESHEET (पूर्वानी आरोप पत्र)"
).replace("Preliminary Chargesheet", "Purvani Chargesheet")

TEMPLATES["court_custody"] = TEMPLATES["remand_request"].replace(
    "APPLICATION FOR POLICE REMAND", "APPLICATION FOR COURT CUSTODY"
).replace("Police Custody Remand for 7 (Seven) Days", "Judicial Custody")

TEMPLATES["medical_letter"] = """
<div style="font-family:Georgia,serif;max-width:800px;margin:0 auto;padding:24px;color:#111;line-height:1.7">
""" + _HEADER.replace("{{ doc_title }}", "MEDICAL EXAMINATION LETTER") + """
<div style="margin-bottom:16px">
  To,<br>
  <div style="margin-left:20px">The Medical Officer,<br>Civil Hospital, Ahmedabad.</div>
</div>
<div style="margin-bottom:16px">
  <b>Subject:</b> Medical Examination of Arrested Accused {{ accused_name }} in FIR No. {{ fir_number }}
</div>
<div style="font-size:13px;margin-bottom:16px">
  The above-named accused has been arrested in connection with FIR No. {{ fir_number }} registered at
  {{ station }}. You are requested to conduct a medical examination and provide a certificate
  regarding the physical condition of the accused. Please examine for: injuries, intoxication, fitness for custody.
</div>
""" + _FOOTER + """
</div>
"""

TEMPLATES["face_id_form"] = """
<div style="font-family:Georgia,serif;max-width:800px;margin:0 auto;padding:24px;color:#111;line-height:1.7">
""" + _HEADER.replace("{{ doc_title }}", "FACE IDENTIFICATION PARADE FORM") + """
<div style="font-size:13px;margin-bottom:20px">
  Conducted at {{ station }} on {{ date }} under supervision of Magistrate.
  Witness: <b>{{ victim_name }}</b> was asked to identify the accused from a group of 8 persons.
</div>
<table style="width:100%;border-collapse:collapse;font-size:13px">
  <tr style="background:#f5f5f5">
    <th style="padding:8px;border:1px solid #ddd">Position</th>
    <th style="padding:8px;border:1px solid #ddd">Name of Person</th>
    <th style="padding:8px;border:1px solid #ddd">Identified?</th>
    <th style="padding:8px;border:1px solid #ddd">Remarks</th>
  </tr>
  {% for i in range(1, 9) %}
  <tr><td style="padding:8px;border:1px solid #ddd;text-align:center">{{ i }}</td><td style="padding:8px;border:1px solid #ddd">________________________</td><td style="padding:8px;border:1px solid #ddd">☐ Yes  ☐ No</td><td style="padding:8px;border:1px solid #ddd"></td></tr>
  {% endfor %}
</table>
""" + _FOOTER + """
</div>
"""


def render_document(doc_type: str, case_data: dict) -> str:
    """Render a legal document from case data using Jinja2 template"""
    template_str = TEMPLATES.get(doc_type)
    if not template_str:
        raise ValueError(f"No template for doc_type: {doc_type}")

    # Prepare template context
    ctx = {
        "doc_title": _get_doc_title(doc_type),
        "case_id": case_data.get("case_id", "—"),
        "fir_number": case_data.get("fir_number", "Pending"),
        "date": datetime.now().strftime("%d %B %Y"),
        "station": case_data.get("police_station", "Ahmedabad Cyber Crime Branch"),
        "victim_name": case_data.get("victim_name", "—"),
        "victim_phone": case_data.get("victim_phone", ""),
        "victim_address": case_data.get("victim_address", ""),
        "amount_defrauded": float(case_data.get("amount_defrauded", 0)),
        "amount_words": _amount_to_words(float(case_data.get("amount_defrauded", 0))),
        "accused_name": case_data.get("accused_name", "Unknown"),
        "accused_phone": case_data.get("accused_phone", ""),
        "accused_address": case_data.get("accused_address", ""),
        "accused_mode": case_data.get("accused_mode", ""),
        "incident_description": case_data.get("incident_description", ""),
        "incident_location": case_data.get("incident_location", ""),
        "ai_sections": case_data.get("ai_sections", []),
        "io_name": case_data.get("io_name", "Investigating Officer"),
        "io_badge": case_data.get("io_badge", "—"),
    }

    try:
        template = jinja_env.from_string(template_str)
        return template.render(**ctx)
    except Exception as e:
        logger.error(f"Template render failed for {doc_type}: {e}")
        return f"<p>Error rendering document: {e}</p>"


def _get_doc_title(doc_type: str) -> str:
    titles = {
        "chargesheet": "CHARGESHEET (आरोप पत्र)",
        "purvani_chargesheet": "PURVANI CHARGESHEET (पूर्वानी)",
        "remand_request": "APPLICATION FOR POLICE REMAND",
        "medical_letter": "MEDICAL EXAMINATION LETTER",
        "seizure_receipt": "SEIZURE RECEIPT (जब्ती पावती)",
        "court_custody": "COURT CUSTODY APPLICATION",
        "panchanama": "ACCUSED PANCHANAMA (पंचनामा)",
        "face_id_form": "FACE IDENTIFICATION PARADE FORM",
    }
    return titles.get(doc_type, doc_type.upper().replace("_", " "))


def _amount_to_words(amount: float) -> str:
    """Convert amount to Indian English words"""
    n = int(amount)
    if n == 0:
        return "Zero Rupees"
    if n >= 10000000:
        return f"Rupees {n/10000000:.1f} Crore"
    if n >= 100000:
        return f"Rupees {n/100000:.1f} Lakh"
    if n >= 1000:
        return f"Rupees {n/1000:.1f} Thousand"
    return f"Rupees {n}"
